### ISSUE TITLE
some users are logged in for ages even they went offline long ago

### ISSUE THREAD

**Issue by quape** [Meteor-Community-Packages/meteor-user-status#111]
Hi there,
I noticed that this great plugin works pretty accurate the most time. But some users (nothing special, e.g. latest Firefox on a Windows machine) are not marked as offline even if they have left the site hours ago. For some reason the event is not triggered.

So what is the best way to fix this? I could set online to false for all users who have logged in say 1 hour ago. But is there a better way?

**Comment by mizzao** [comment]
Might be related to #29, one of our earliest bugs. But since this is dependent on Meteor's DDP connections anyway, it might not be something we can fix here. You might want to just debug the situation a bit and see what you find.

**Comment by quape** [comment]
Oh thanks mizzao, it may be the same problem. I will add some set-offline-after-5-mins as described in #29. That should be enough.
