### ISSUE TITLE
Transfer to Meteor-Community-Packages

### ISSUE THREAD

**Issue by mizzao** [Meteor-Community-Packages/meteor-user-status#122]
Hey @StorytellerCZ,

I transferred all my packages to @Meteor-Community-Packages. This includes:

https://github.com/Meteor-Community-Packages/meteor-user-status
https://github.com/Meteor-Community-Packages/meteor-timesync
https://github.com/Meteor-Community-Packages/meteor-partitioner
https://github.com/Meteor-Community-Packages/meteor-autocomplete

We probably want to transfer the maintainers over as well. Let me know how you typically handle that (I don't have permissions to create/edit teams or anything).

**Comment by StorytellerCZ** [comment]
Nice, do you want to have one team for all of these?
Right now the old collaborators are still set. With the creation of team we would move them there unless they had admin privileges.

**Comment by mizzao** [comment]
`user-status` and `timesync` are closely related, so it would make sense to have one team for that.

`partitioner` is loosely related / interoperates with the above, and is also written in coffee, so could be on the same team.

`autocomplete` is unrelated, but also written in coffee, so it wouldn't hurt to be on the same team if there is someone comfortable maintaining coffee (or translating to TypeScript).

Maybe just add one or two teams based on how you've been organizing things so far? Here's also a message I have been sending people to publish new versions:

--------------------

If you'd like to directly publish new versions of the package, just send me your Meteor username and I'll add you as a maintainer.

--------------------

I usually use the following simple procedure for publishing, although you can do what works for you:

- [ ]  Pick an appropriate incremented version number v0.x.y (e.g. 0.4.0 becomes 0.4.1 or 0.5.0 depending on how much changed)
- [ ]  Update the `History.md` file to reflect all changes that will be in the new version. If you've been keeping it up to date (and it appears you have), this just involves inserting the above version number below vNEXT.
- [ ]  Update this version number in `package.js`.
- [ ]  git commit (but don't push yet).
- [ ]  Try `meteor publish`
- [ ]  If everything worked, `git tag v0.x.y` and push the tag (`git push origin v0.x.y`; this allows others to find the code for this version) and merge into master and push that too. (If you aren't rebasing the feature branch you may want to merge first before publishing)
- [ ] If publishing didn't work, you can fix things, amend the commit as necessary, then tag and push after verifying that it went through.

Thanks so much for your help!

**Comment by StorytellerCZ** [comment]
For now I think one team will be enough. The main task is to find maintainers. I have almost identical publishing approach.
I also think that we might want to decafinate the code to be more accessible. But first priority is an appropriate name for the team and finding maintainers.

**Comment by wreiske** [comment]
I have decaffeinated versions on a git branch that I converted over to ts. I haven't had time recently to get it ready to push out to the world. I may set some time aside to clean it up.

**Comment by mizzao** [comment]
@wreiske I'd suggest push first, fix later. Once you push a decaffeinated (especially TS) version, someone is more likely to jump in and help.

**Comment by StorytellerCZ** [comment]
@wreiske At least start the PR, we can fix things in there.

**Comment by wreiske** [comment]
@mizzao I don't have access to push to a new branch. I was able to create a new branch, but pushing is causing a 403.

**Comment by mizzao** [comment]
@StorytellerCZ can you check repo/team permissions? Might have changed since the transfer.

**Comment by StorytellerCZ** [comment]
@mizzao @wreiske Created a team called [meteor-utils](https://github.com/orgs/Meteor-Community-Packages/teams/meteor-utils) where I moved the packages for now. The old permissions probably got downgraded so I restored a bit of that.
I'm closing this issue and discussion can continue on the team and issues/PRs.
