### ISSUE TITLE
Remove usage of underscore

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/meteor-user-status#126]
After #124 is merged we should remove the remaining use of underscore. This is primarily that it should not be needed and to lighten the app bundle size.

If some underscore functionality is needed only those specific functions should be imported from npm to minimize bundle size.

**Comment by foysalit** [comment]
I would like to take this one @StorytellerCZ not sure if it is needed to announce or get assigned specifically?

**Comment by wreiske** [comment]
> I would like to take this one @StorytellerCZ not sure if it is needed to announce or get assigned specifically? 

If you'd like to open a PR we would be happy to review it :).

**Comment by StorytellerCZ** [comment]
@foysalit You have been assigned! Looking forward to merge the PR.
