### ISSUE TITLE
UserStatus no longer global

### ISSUE THREAD

**Issue by rijk** [Meteor-Community-Packages/meteor-user-status#129]
I think this has to do with the 'decaffinating' of the package; after updating to 1.0.0 using `UserStatus` without importing no longer works. To get it to work, you have to do:

```
import { UserStatus } from 'meteor/mizzao:user-status'
```

Maybe we should mention this in the Readme (and History as a breaking change)?

**Comment by mizzao** [comment]
Good suggestion. I also noticed v1.0.0 wasn't tagged, and perhaps something we should consider as described in #125.

**Comment by wreiske** [comment]
> Good suggestion. I also noticed v1.0.0 wasn't tagged, and perhaps something we should consider as described in #125.

Please see https://github.com/orgs/Meteor-Community-Packages/teams/meteor-utils/discussions/1/comments/12

**Comment by sotarules** [comment]
Yes this caught me and scared me, I moved to Windows 10, and UserStatus wasn't there, I was under the impression I had mis-configured the new system.  I finally noticed that the version was different comparing **packages** to my Windows 7 machine.  "Decaffinated" is funny.

**Comment by StorytellerCZ** [comment]
Added notice to this to history file.
