### ISSUE TITLE
TravisCI build is failing

### ISSUE THREAD

**Issue by wreiske** [Meteor-Community-Packages/meteor-user-status#137]
![Screen Shot 2020-10-20 at 9 47 18 AM](https://user-images.githubusercontent.com/6295044/96618132-66549100-12b9-11eb-8898-72a94b92c372.png)

Started failing with this commit e0c6ccd8f345458deb8516db280eff0b278a2f12

**Comment by mizzao** [comment]
IIRC, the Travis script I was using didn't lock a Meteor version, so the tests could be failing due to a Meteor version bump rather than any commit change. Sorry about that :S

**Comment by StorytellerCZ** [comment]
Fixed in #186
