### ISSUE TITLE
Logging out and back in in the same browser with multiple windows open breaks tracking

### ISSUE THREAD

**Issue by mizzao** [Meteor-Community-Packages/meteor-user-status#2]
If two windows of the same browser are open (different sessions) and a user logs out and back in as someone else, the tracking breaks because the other session will get authenticated as the new user as well but retains the same socket that the previous user was using. Numbers will be fudged until the second session ends, counting toward the old user.

This isn't a huge deal right now because it really only comes up when testing apps, but I'm recording it here for reference.

**Comment by scheung38** [comment]
But I am stil seeing the same thing of different windows, with one application logout, the other window also get logout?
