### ISSUE TITLE
Feature Request: Add ability to track users on a per page basis as opposed to entire app

### ISSUE THREAD

**Issue by Scalahansolo** [Meteor-Community-Packages/meteor-user-status#28]
Currently, the app only tracks a user as it is connected to the server. It would be incredibly useful if I could track the users on a specific page. This would be incredibly useful in a chat app (like my own) where you want to know only the users that are currently sitting on a particular page.

**Comment by tsega** [comment]
@mizzao has this been implemented, yet? Just to illustrate a point, a user (authenticated or anonymous) can move away from a page/route in three different ways:

1. The user moves to another page/route, something Iron Router should handle.
2. The user closes a tab.
3. The user closes the browser.

From what I've noticed, from experimenting your package, point 2 & 3 are different kinds of events.

**Comment by mizzao** [comment]
No, not implemented yet; however #2 and #3 should be the same unless there are two tabs open (sharing the same authenticated user).

It's difficult for me to implement features that I am not personally using in this package, but I'd welcome pull requests!

**Comment by MichaelJCole** [comment]
Hey, I was looking for a similar feature.  This seems like it could be implemented just with IronRouter.  Update the `user.profile.lastRoute` in a hook on each route.

Then a user's current route is:  `(user.status.online) ? user.profile.lastRoute : false`.

Would you need something more than that?

**Comment by onedr0p** [comment]
To get this working in FlowRouter I set up this code client side (this requires lodash, but you can use another method on this line `if (_.has(FlowRouter.current(), 'context.hash')) {`

```js
if (Meteor.isClient) {
  // Update users.status.lastRoute
  // include hash in url if present
  Tracker.autorun(function () {
    if (Meteor.userId()) {
      FlowRouter.watchPathChange();
      var currentPath = FlowRouter.current().path;
      if (_.has(FlowRouter.current(), 'context.hash')) {
        currentPath = currentPath + '#' + FlowRouter.current().context.hash;
      }

      if (currentPath) {
        Meteor.users.update({_id: Meteor.userId() }, { $set: { 'status.lastRoute': currentPath } } );
      }
    }
  });
}
```

This can be extended further to have it track in another collection, like `users_status_history`
