### ISSUE TITLE
Is there a way to avoid relogging the user on reload?

### ISSUE THREAD

**Issue by ClarkGH** [Meteor-Community-Packages/meteor-user-status#55]
I notice the connectionLogin and connectionLogout events will count every refresh or visit to another route as a new login. Is there a simple way to bypass the update and only count when the user logs in/out?

**Comment by mizzao** [comment]
That certainly won't happen if you use something like Iron Router which will change the route without reloading the app. But since Meteor doesn't support connection resuming at the moment, we can't tell the difference between a user leaving and returning vs. just reloading.

**Comment by THPubs** [comment]
Is it possible to stop this behavior in FlowRouter?
