### ISSUE TITLE
connectionIdle event ( server api ) not triggered in IOS devices

### ISSUE THREAD

**Issue by binarytracer** [Meteor-Community-Packages/meteor-user-status#83]
@mizzao, thanks for this package you given to us, youreally save our time developing our first meteor app, considering our app involve some user status.

currently we are implementing the server api ( 3 out of 4 events ), we notice that in IOS devices 
events like connectionIdle, connectionActive is not activating when the app is idled, I would like to hear if you have some insights on this stuff.

**Comment by mizzao** [comment]
Take a look at how we fixed #47.
